from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER
import io
import base64
import matplotlib.pyplot as plt

def generate_pdf_report(df_summary, generated_plots, model_results, cluster_results):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # Custom style for centering text
    styles.add(ParagraphStyle(name='Center', alignment=TA_CENTER))
    styles.add(ParagraphStyle(name='LeftAlign', alignment=TA_CENTER))

    # Title Page
    story.append(Paragraph("<b>AutoDS AI - Comprehensive Data Report</b>", styles['h1']))
    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph("<i>Autonomous Data Scientist System</i>", styles['Center']))
    story.append(Spacer(1, 0.8 * inch))
    story.append(Paragraph("Generated by Google Colab AI", styles['Center']))
    story.append(PageBreak())

    # 1. Dataset Summary
    story.append(Paragraph("<b>1. Dataset Summary</b>", styles['h2']))
    story.append(Spacer(1, 0.2 * inch))

    if 'Raw Data Head' in df_summary:
        story.append(Paragraph("<b>1.1 Raw Dataset Head:</b>", styles['h3']))
        story.append(Paragraph(df_summary['Raw Data Head'], styles['Normal']))
        story.append(Spacer(1, 0.2 * inch))

    for key, value in df_summary.items():
        if key not in ['Raw Data Head', 'Data Types', 'Statistical Summary']:
            story.append(Paragraph(f"<b>{key}:</b> {value}", styles['Normal']))
    story.append(Spacer(1, 0.2 * inch))

    if 'Data Types' in df_summary:
        story.append(Paragraph("<b>1.2 Data Types:</b>", styles['h3']))
        story.append(Paragraph(df_summary['Data Types'], styles['Normal']))
        story.append(Spacer(1, 0.2 * inch))

    if 'Statistical Summary' in df_summary:
        story.append(Paragraph("<b>1.3 Statistical Summary:</b>", styles['h3']))
        story.append(Paragraph(df_summary['Statistical Summary'], styles['Normal']))
        story.append(Spacer(1, 0.4 * inch))
    story.append(PageBreak())

    # 2. Visualizations
    story.append(Paragraph("<b>2. Visualizations</b>", styles['h2']))
    story.append(Spacer(1, 0.2 * inch))

    for plot_data in generated_plots:
        story.append(Paragraph(f"<b>{plot_data['name']}</b>", styles['h3']))
        story.append(Spacer(1, 0.1 * inch))

        if plot_data['type'] == 'matplotlib':
            # Save matplotlib figure to a bytes buffer
            img_buffer = io.BytesIO()
            plot_data['figure'].savefig(img_buffer, format='png', bbox_inches='tight')
            img_buffer.seek(0)
            img = Image(img_buffer, width=6*inch, height=4*inch) # Adjust size as needed
            story.append(img)
            story.append(Spacer(1, 0.2 * inch))
            # Close the matplotlib figure to free memory
            plt.close(plot_data['figure'])
        elif plot_data['type'] == 'plotly':
            # For Plotly, we would need to convert it to a static image first
            # This example assumes all saved plots are matplotlib for simplicity, but can be extended.
            # For Plotly, you'd typically use fig.write_image(file_or_buffer, format='png')
            story.append(Paragraph("<i>Plotly chart placeholder (requires static image conversion)</i>", styles['Normal']))
        story.append(Spacer(1, 0.2 * inch))
    story.append(PageBreak())

    # 3. Model Performance
    story.append(Paragraph("<b>3. Model Performance</b>", styles['h2']))
    story.append(Spacer(1, 0.2 * inch))
    if model_results:
        story.append(Paragraph(f"<b>Model Type:</b> {model_results.get('model_type', 'N/A')}", styles['Normal']))
        story.append(Paragraph(f"<b>Selected Model:</b> {model_results.get('selected_model_name', 'N/A')}", styles['Normal']))
        story.append(Paragraph(f"<b>Target Column:</b> {model_results.get('target_col', 'N/A')}", styles['Normal']))
        story.append(Paragraph(f"<b>{model_results.get('metric_name', 'Metric')}:</b> {model_results.get('metric_value', 'N/A'):.2f}", styles['Normal']))

        if model_results.get('tuning_enabled'):
            story.append(Spacer(1, 0.1 * inch))
            story.append(Paragraph("<b>Hyperparameter Tuning Results:</b>", styles['h3']))
            story.append(Paragraph(f"<b>Tuning Method:</b> {model_results.get('tuning_method', 'N/A')}", styles['Normal']))
            story.append(Paragraph("<b>Best Parameters:</b>", styles['Normal']))
            for param, val in model_results.get('best_params', {}).items():
                story.append(Paragraph(f"    - {param}: {val}", styles['Normal']))
    else:
        story.append(Paragraph("<i>No model training data available.</i>", styles['Normal']))
    story.append(Spacer(1, 0.4 * inch))
    story.append(PageBreak())

    # 4. Clustering Results
    story.append(Paragraph("<b>4. Clustering Results</b>", styles['h2']))
    story.append(Spacer(1, 0.2 * inch))
    if cluster_results:
        for cluster_type, results in cluster_results.items():
            story.append(Paragraph(f"<b>{cluster_type} Clustering:</b>", styles['h3']))
            story.append(Paragraph(f"<b>Features Used:</b> {', '.join(results.get('features', []))}", styles['Normal']))
            story.append(Paragraph(f"<b>Silhouette Score:</b> {results.get('silhouette_score', 'N/A'):.2f}", styles['Normal']))
            if cluster_type == "K-Means":
                story.append(Paragraph(f"<b>Number of Clusters (K):</b> {results.get('n_clusters', 'N/A')}", styles['Normal']))
            elif cluster_type == "DBSCAN":
                story.append(Paragraph(f"<b>EPS:</b> {results.get('eps', 'N/A')}", styles['Normal']))
                story.append(Paragraph(f"<b>Min Samples:</b> {results.get('min_samples', 'N/A')}", styles['Normal']))
                story.append(Paragraph(f"<b>Noise Points:</b> {results.get('noise_points', 'N/A')}", styles['Normal']))
            story.append(Spacer(1, 0.2 * inch))

            # Add cluster distribution plot if available
            if results.get('distribution_plot'):
                dist_img_buffer = io.BytesIO()
                results['distribution_plot'].savefig(dist_img_buffer, format='png', bbox_inches='tight')
                dist_img_buffer.seek(0)
                dist_img = Image(dist_img_buffer, width=5*inch, height=3*inch)
                story.append(Paragraph("<b>Cluster Distribution:</b>", styles['Normal']))
                story.append(dist_img)
                plt.close(results['distribution_plot'])

            # Add cluster visualization plot if available
            if results.get('visualization_plot'):
                viz_img_buffer = io.BytesIO()
                results['visualization_plot'].savefig(viz_img_buffer, format='png', bbox_inches='tight')
                viz_img_buffer.seek(0)
                viz_img = Image(viz_img_buffer, width=6*inch, height=4*inch)
                story.append(Paragraph("<b>Cluster Visualization:</b>", styles['Normal']))
                story.append(viz_img)
                plt.close(results['visualization_plot'])

            story.append(Spacer(1, 0.4 * inch))
    else:
        story.append(Paragraph("<i>No clustering data available.</i>", styles['Normal']))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
